services:
  nginx:
    image: nginx
    container_name: nginx
    volumes: 
      - ${NGINX_CONFIG_ROOT}:/etc/nginx
    ports:
      - ${NGINX_HTTP_PORT}:${NGINX_HTTP_PORT}/tcp
      - ${NGINX_HTTPS_PORT}:${NGINX_HTTPS_PORT}/tcp
    restart: unless-stopped
    depends_on:
      - qbit
      - rcon
    networks:
      - ahoyt-internal

networks:
  ahoyt-internal:
    external: true
