services:
  qbit:
    container_name: qbit
    image: lscr.io/linuxserver/qbittorrent:latest
    ports:
      - ${QBIT_WEB_PORT}:${QBIT_WEB_PORT}
      - ${QBIT_TORRENT_PORT}:${QBIT_TORRENT_PORT}
    environment:
     - PUID=1000
     - PGID=1000
     - WEBUI_PORT=${QBIT_WEB_PORT}
     - TZ=America/Denver
     - TORRENTING_PORT=${QBIT_TORRENT_PORT}
    volumes:
      - ${QBIT_CONFIG}:/config/qBittorrent
      - ${QBIT_CACHE}:/cache/qBittorrent
      - ${QBIT_TORRENTS}:/downloads/torrents
      - ${ISO_ROOT}:/downloads/iso
      - ${TV_ROOT}:/downloads/tv-shows
      - ${MOVIES_ROOT}:/downloads/movies
      - ${MUSIC_ROOT}:/downloads/music

